name: ping_my_therapist
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^17.0.0
  dio: ^5.9.2
  flutter_dotenv: ^6.0.1
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.6

  # Networking & utilities
  http: ^1.4.0
  intl: ^0.20.2
  uuid: ^4.5.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.3.8
  custom_lint: ^0.5.11

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/icons/nav-icons/
    - assets/images/
    - assets/gifs/
    - assets/emojis/annoyance/
    - assets/emojis/energy/
    - assets/emojis/mood-scale/
    - assets/emojis/others/
    - assets/emojis/positive/
    - assets/emojis/stressed/
    - assets/emojis/vibes/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand/Quicksand_Bold.otf
          weight: 700
        - asset: assets/fonts/quicksand/Quicksand_Book.otf
          weight: 400
        - asset: assets/fonts/quicksand/Quicksand_Light.otf
          weight: 300
        - asset: assets/fonts/quicksand/Quicksand_Bold_Oblique.otf
          weight: 700
          style: italic
        - asset: assets/fonts/quicksand/Quicksand_Book_Oblique.otf
          weight: 400
          style: italic
        - asset: assets/fonts/quicksand/Quicksand_Light_Oblique.otf
          weight: 300
          style: italic

    - family: quicksand
      fonts:
        - asset: assets/fonts/quicksand/Quicksand_Bold.otf
          weight: 700
        - asset: assets/fonts/quicksand/Quicksand_Book.otf
          weight: 400
        - asset: assets/fonts/quicksand/Quicksand_Light.otf
          weight: 300
        - asset: assets/fonts/quicksand/Quicksand_Bold_Oblique.otf
          weight: 700
          style: italic
        - asset: assets/fonts/quicksand/Quicksand_Book_Oblique.otf
          weight: 400
          style: italic
        - asset: assets/fonts/quicksand/Quicksand_Light_Oblique.otf
          weight: 300
          style: italic

    - family: GeneralSans
      fonts:
        - asset: assets/fonts/General Sans/GeneralSans-Regular.otf
          weight: 400
        - asset: assets/fonts/General Sans/GeneralSans-Medium.otf
          weight: 500
        - asset: assets/fonts/General Sans/GeneralSans-Semibold.otf
          weight: 600
        - asset: assets/fonts/General Sans/GeneralSans-Bold.otf
          weight: 700
        - asset: assets/fonts/General Sans/GeneralSans-Light.otf
          weight: 300
        - asset: assets/fonts/General Sans/GeneralSans-Extralight.otf
          weight: 200
        - asset: assets/fonts/General Sans/GeneralSans-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/General Sans/GeneralSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/General Sans/GeneralSans-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/General Sans/GeneralSans-BoldItalic.otf
          weight: 700
          style: italic

    - family: General Sans
      fonts:
        - asset: assets/fonts/General Sans/GeneralSans-Regular.otf
          weight: 400
        - asset: assets/fonts/General Sans/GeneralSans-Medium.otf
          weight: 500
        - asset: assets/fonts/General Sans/GeneralSans-Semibold.otf
          weight: 600
        - asset: assets/fonts/General Sans/GeneralSans-Bold.otf
          weight: 700
        - asset: assets/fonts/General Sans/GeneralSans-Light.otf
          weight: 300
        - asset: assets/fonts/General Sans/GeneralSans-Extralight.otf
          weight: 200
        - asset: assets/fonts/General Sans/GeneralSans-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/General Sans/GeneralSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/General Sans/GeneralSans-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/General Sans/GeneralSans-BoldItalic.otf
          weight: 700
          style: italic
