// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── Android ─────────────────────────────────────────────────────────────
  // Values from google-services.json (project: pingmytherapist)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2riMkuYteX7FxVinjcvWsX333HMcRhc4',
    appId: '1:210120645289:android:5d8edb902b968913c1e7b8',
    messagingSenderId: '210120645289',
    projectId: 'pingmytherapist',
    storageBucket: 'pingmytherapist.firebasestorage.app',
  );

  // ── iOS / macOS ──────────────────────────────────────────────────────────
  // TODO: Register the iOS app in Firebase Console (pingmytherapist project)
  //       and replace these values with the ones from GoogleService-Info.plist.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: 'REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: '210120645289',
    projectId: 'pingmytherapist',
    storageBucket: 'pingmytherapist.firebasestorage.app',
    iosBundleId: 'com.pingmytherapist.pingMyTherapist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: 'REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: '210120645289',
    projectId: 'pingmytherapist',
    storageBucket: 'pingmytherapist.firebasestorage.app',
    iosBundleId: 'com.pingmytherapist.pingMyTherapist',
  );

  // ── Web ──────────────────────────────────────────────────────────────────
  // TODO: Register the web app in Firebase Console (pingmytherapist project)
  //       and replace these values.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_WEB_API_KEY',
    appId: 'REPLACE_WITH_WEB_APP_ID',
    messagingSenderId: '210120645289',
    projectId: 'pingmytherapist',
    authDomain: 'pingmytherapist.firebaseapp.com',
    storageBucket: 'pingmytherapist.firebasestorage.app',
  );

  // ── Windows ──────────────────────────────────────────────────────────────
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REPLACE_WITH_WEB_API_KEY',
    appId: 'REPLACE_WITH_WEB_APP_ID',
    messagingSenderId: '210120645289',
    projectId: 'pingmytherapist',
    authDomain: 'pingmytherapist.firebaseapp.com',
    storageBucket: 'pingmytherapist.firebasestorage.app',
  );
}
